### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/agreement#4]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] agreement - By @FrancoMaxime - #12
- [x] agreement_legal - By @urvisha-serpentcs - #8
- [ ] agreement_legal_sale - By @adasatorres - #45
- [ ] agreement_project - By @len-foss - #15
- [x] agreement_rebate - By @ao-landoo - #21
- [x] agreement_sale - By @adasatorres - #44
- [x] agreement_serviceprofile - By @luisDIXMIT - #37

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by gomezgleonardob** [comment]
I can considerate migrate agreeement_repair?

**Comment by ao-landoo** [comment]
I'm migrating `agreement_rebate`
